### ISSUE TITLE
$_SERVER['PHP_SELF'] & XSS

### ISSUE THREAD

**Issue by NinjaSentry** [LolDatSec/Web-Firewall#1]
Hi. It might be a good idea to escape the $_SERVER['PHP_SELF'] vars to avoid any XSS issues.

https://github.com/LolDatSec/Web-Firewall/blob/master/l7prot.php#L51
https://github.com/LolDatSec/Web-Firewall/blob/master/l7prot.php#L53

```php
<?php
htmlspecialchars( $_SERVER['PHP_SELF'], ENT_QUOTES, 'UTF-8' );
?>
```

**Comment by LolDatSec** [comment]
Sorry forgot to put double quotes.

Still, this is a discontinued project.

**Comment by NinjaSentry** [comment]
No worries. Using CloudFlare was a really bad idea anyway.

**Comment by LolDatSec** [comment]
It's really only good exposing every visitor to mitm.

And maybe a firewall.
Otherwise I am using a new apache mod to handle all this and using a IP based local blacklist (or cloudflare for "extra security".)

**Comment by NinjaSentry** [comment]
I like the apache mod idea. Extra security is always good.. 

Have you seen this test ? 
http://www.slideshare.net/zeroscience/cloudflare-vs-incapsula-vs-modsecurity
http://tonyonsecurity.com/2013/03/09/protect-your-website-vulnerabilities-with-a-waf-new-compairson-report-cloudflare-vs-incapsula-vs-modsecurity/

This tool might be useful for you 
https://github.com/prbinu/yipfilter

**Comment by LolDatSec** [comment]
Thanks.
